# Use pre-built base image with Flux and all dependencies
FROM ghcr.io/llnl/spindle-base:latest AS builder
ARG replicas=4
ENV workers=${replicas}
USER root

ARG USER=fluxuser
ARG CONFIG_ROOT=containers/debug/spindle-flux-ubuntu

# Configure Flux for this specific node count
ENV STATE_DIR=/var/lib/flux
COPY ${CONFIG_ROOT}/flux/imp.toml /etc/flux/imp/conf.d/
COPY ${CONFIG_ROOT}/flux/generate-broker-toml.sh /tmp/generate-broker-toml.sh
RUN /tmp/generate-broker-toml.sh ${workers} > /etc/flux/config/broker.toml && \
    mkdir -p /mnt/curve && \
    flux keygen /mnt/curve/curve.cert && \
    flux R encode --hosts="node-[1-${workers}]" > /etc/flux/system/R && \
    chown -R ${USER}:${USER} /run/flux ${STATE_DIR} /mnt/curve/curve.cert /etc/flux/system/R /etc/flux/config/broker.toml

# Build Spindle
WORKDIR /home/${USER}
COPY . /home/${USER}/Spindle
COPY ${CONFIG_ROOT}/scripts/build_spindle.sh /home/${USER}/build_spindle.sh
RUN ./build_spindle.sh

RUN chown -R ${USER}:${USER} /home/${USER}

USER ${USER}
COPY ${CONFIG_ROOT}/scripts/flux_healthcheck.sh ./
COPY ${CONFIG_ROOT}/scripts/entrypoint.sh ./
ENV PATH=/home/${USER}/Spindle-inst/bin:${PATH}

ENTRYPOINT /bin/bash ./entrypoint.sh
