#!/bin/sh

if [ "x$SPINDLE_LD_PRELOAD" != "x" ] ; then
    $SPINDLE $SPINDLE_FLAGS $SPINDLE_OPTS --launcher=serial bash -c "LD_PRELOAD=$SPINDLE_LD_PRELOAD $*"
else
    $SPINDLE $SPINDLE_FLAGS $SPINDLE_OPTS --launcher=serial $*
fi
