#!/bin/bash

export SPINDLE_TEST_ARGS="$@"
export SPINDLE_BLUEGENE="BLUEGENE_TEST"
export TEST_RM="TEST_RESOURCE_MANAGER"
export GLOBAL_RESULT=0

rm -f spindle_output* *.core

declare -A SPINDLE_TESTS=(
    [dependency_push]="--dependency --push"
    [dlopen_push]="--dlopen --push"
    [dlreopen_push]="--dlreopen --push"
    [thrdopen_push]="--thrdopen --push"
    [reorder_push]="--reorder --push"
    [partial_push]="--partial --push"
    [ldpreload_push]="--ldpreload --push"
    [spindleapi_push]="--spindleapi --push"
    [dependency_pull]="--dependency --pull"
    [dlopen_pull]="--dlopen --pull"
    [dlreopen_pull]="--dlreopen --pull"
    [thrdopen_pull]="--thrdopen --pull"
    [reorder_pull]="--reorder --pull"
    [partial_pull]="--partial --pull"
    [ldpreload_pull]="--ldpreload --pull"
    [spindleapi_pull]="--spindleapi --pull"
    [dependency_numa]="--dependency --numa"
    [dlopen_numa]="--dlopen --numa"
    [dlreopen_numa]="--dlreopen --numa"
    [thrdopen_numa]="--thrdopen --numa"
    [reorder_numa]="--reorder --numa"
    [partial_numa]="--partial --numa"
    [ldpreload_numa]="--ldpreload --numa"
    [spindleapi_numa]="--spindleapi --numa"
    [dependency_fork]="--dependency --fork"
    [dlopen_fork]="--dlopen --fork"
    [dlreopen_fork]="--dlreopen --fork"
    [thrdopen_fork]="--thrdopen --fork"
    [reorder_fork]="--reorder --fork"
    [partial_fork]="--partial --fork"
    [ldpreload_fork]="--ldpreload --fork"
    [spindleapi_fork]="--spindleapi --fork"
    [dependency_forkexec]="--dependency --forkexec"
    [dlopen_forkexec]="--dlopen --forkexec"
    [dlreopen_forkexec]="--dlreopen --forkexec"
    [thrdopen_forkexec]="--thrdopen --forkexec"
    [reorder_forkexec]="--reorder --forkexec"
    [partial_forkexec]="--partial --forkexec"
    [ldpreload_forkexec]="--ldpreload --forkexec"
    [spindleapi_forkexec]="--spindleapi --forkexec"
    [dependency_chdir]="--dependency --chdir"
    [dlopen_chdir]="--dlopen --chdir"
    [dlreopen_chdir]="--dlreopen --chdir"
    [thrdopen_chdir]="--thrdopen --chdir"
    [reorder_chdir]="--reorder --chdir"
    [partial_chdir]="--partial --chdir"
    [ldpreload_chdir]="--ldpreload --chdir"
    [spindleapi_chdir]="--spindleapi --chdir"
    [dependency_preload]="--dependency --preload"
    [dlopen_preload]="--dlopen --preload"
    [dlreopen_preload]="--dlreopen --preload"
    [thrdopen_preload]="--thrdopen --preload"
    [reorder_preload]="--reorder --preload"
    [partial_preload]="--partial --preload"
    [ldpreload_preload]="--ldpreload --preload"
    [spindleapi_preload]="--spindleapi --preload"
    [serial_spindle_exec_test]="--serial ./spindle_exec_test"
    [serial_symbind_test]="--serial ./symbind_test"
    [serial_interpreter_test]="--serial ./interpreter_test"
)

if test "x$TEST_RM" != "xserial"; then
    export SESSION_ID=$(./run_driver --start-session)
    SPINDLE_TESTS+=(
        [dependency_session]="--dependency --session"
        [dlopen_session]="--dlopen --session"
        [dlreopen_session]="--dlreopen --session"
        [thrdopen_session]="--thrdopen --session"
        [reorder_session]="--reorder --session"
        [partial_session]="--partial --session"
        [ldpreload_session]="--ldpreload --session"
        [spindleapi_session]="--spindleapi --session"
        [end-session_$SESSION_ID]="--end-session --$SESSION_ID"
    )
fi

for testname in "${!SPINDLE_TESTS[@]}"   # Iterate over the keys in the associative array
do
    # Run the benchmark, with the addition of start and elapsed time.
    echo $(date) Starting ${testname} "${SPINDLE_TESTS[$testname]}"
    ARGS="${SPINDLE_TESTS[$testname]}"
    ./run_driver ${ARGS}
    RESULT=$?
    if [[ $? != 0 ]]; then export GLOBAL_RESULT=-1; fi

    # All result directories begin with _ for easy tarring afterwards.
    # Repeated tests with identical results will land in the same directory.
    # Runs that don't result in logs or corefiles will generate empty directories.
    # The "find" uses a couple of obscure features:
    #   {} gets replaced with every matching file (due to the trailing "+")
    #   If no files match, the "mv" command doesn't execute, thus no error.
    #   "-o" is logical-OR.
    tag=_${RESULT}_${testname}
    mkdir -p $tag
    find . -maxdepth 1 \( -name '*.core' -o -name 'spindle_output*' \) -exec mv -t ./$tag {} +

done

if [[ $GLOBAL_RESULT != 0 ]]; then
    echo SOME TESTS FAILED
    exit -1
fi
echo ALL TESTS PASSED
unset SESSION_ID
exit 0
